name: ip-omp
channels:
  - defaults
  - pytorch
dependencies:
  - gpustat=0.6.0
  - matplotlib=3.8.0
  - numpy=1.26.2
  - pip=23.3.1
  - python=3.11
  - pytorch=2.1.1
  - rich=13.3.5
  - seaborn=0.12.2
  - tqdm=4.65.0
  - typer=0.9.0
  - pip:
      - polars==0.19.19